---
version: '2.0'
services:
  miner:
    image: pengdocker/wownero:v3.0
    env:
      - ADDR=<your-addr>
      - SPENDKEY=<your-spendkey>
      - THREAD=8
    expose:
      - port: 22
        as: 22
        to:
          - global: true
profiles:
  compute:
    miner:
      resources:
        cpu:
          units: 8
        memory:
          size: 2.5Gi
        storage:
          size: 6Gi
  placement:
    miner:
      pricing:
        miner:
          denom: uakt
          amount: 100000
deployment:
  miner:
    miner:
      profile: miner
      count: 1